/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'webonise' at '16/2/16 10:21 AM' with Gradle 2.5
 *
 * @author webonise, @date 16/2/16 10:21 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
