/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'webonise' at '16/2/16 10:21 AM' with Gradle 2.5
 *
 * @author webonise, @date 16/2/16 10:21 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
